team blog post
upday/upday.github.io pull request #48
Opened 2017-02-22 14:13 UTC by florina-muntenescu

2017-02-22 14:15 UTC, pkrauss-asideas commented on _posts/blog/2017-02-22-team_cut_story.md
> +excerpt: A short story about how to measure a team cut experiment. We change teams a few times already – this article shows how can we learn which set up was actually more productive and how to perfo
changed teams

2017-02-22 15:05 UTC, rbordo requested changes
I would double check the text with a native speaker and then review again.

2017-02-22 15:05 UTC, rbordo commented on _data/authors.yml
> +  bio_long: "Johannes works as an Product Owner at upday telling stories about value."
a Product Owner

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +title: "A Team Cut Story"
Sure about "Team Cut" and not "Team Cutting"?

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +excerpt: A short story about how to measure a team cut experiment. We change teams a few times already – this article shows how can we learn which set up was actually more productive and how to perfo
"team cutting" and "changed teams"

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +excerpt: A short story about how to measure a team cut experiment. We change teams a few times already – this article shows how can we learn which set up was actually more productive and how to perfo
The sentence doesn't feel right in general.

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +It is the challenge for each team member to adapt quickly to new teams, skills and goals. I would like to share how we approach building stronger teams and to have a checklist for myself when a new t
a challenge?
you cannot adapt to skills you can only build them
to share with you?

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +**As a** Product Owner **I want** to set up teams quickly and efficiently in order to get them up ‘n’ running fast and deliver the highest value.
what kind of value?

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +* Calculate the <a href="http://blackswanfarming.com/cost-of-delay-divided-by-duration/" target="blank">CD3</a> (cost of delay/duration) and <a href="http://www.scaledagileframework.com/wsjf/" target
I  would rather write "cost of delay divided by duration", other wise the abbreviation doesn't make sense.

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +	* Communication tool (slack, skype, email etc.)
Slack, Skype, Jjira, Trello, etc. are trademarks. Therefore I would write them with capital letter.

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +We already made several experiments with the team setup without really being able to measure the outcomes. We also realised that not all our needs are covered by the existing experiments. We decided
"But we realized not all our goals were met anyway."?
put "introduced by..." into the brackets as well

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +	* How much time does it take for feature from done to production?
for a feature

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +* <a link="http://www.slideshare.net/management30/the-happiness-of-workers/7-Engagement_probablycorrelates_with_satisfactionand_happinessBut" target="blank">Team happiness</a>
There's no link for "Team happiness." 
How is it measured?

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +It’s also interesting to visualise the amount of meetings we have, to see how effectively we communicate and how much ‘focus time’ is left for each sprint.
how effective our communication is

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +* Team set up is agreed with agile coach / scrum master / team-cut captain
Team setup

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +	*	Planning and progress (jira, trello) – setup corresponding meetings
set up corresponding meetings

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +Acceptance Criteria:
Using Present in acceptance criteria doesn't feel right (next bullet points). Times are mixed anyway.

2017-02-22 15:05 UTC, rbordo commented on _posts/blog/2017-02-22-team_cut_story.md
> +* Epics for projects communicate clearly user/business value and metrics (OKRs) to measure the success of an epic.
"clearly communicate" but "clearly define" would be better 
What are OKRs?

2017-02-22 17:25 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +excerpt: A short story about how to measure a team cut experiment. We change teams a few times already – this article shows how can we learn which set up was actually more productive and how to perfo
corrected

2017-02-22 17:25 UTC, JTheilmann commented on _data/authors.yml
> +  bio_long: "Johannes works as an Product Owner at upday telling stories about value."
corrected

2017-02-22 17:26 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +title: "A Team Cut Story"
corrected

2017-02-23 10:22 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +	* How much time does it take for feature from done to production?
corrected

2017-02-23 10:28 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +* Epics for projects communicate clearly user/business value and metrics (OKRs) to measure the success of an epic.
I added a link to OKR

2017-02-23 10:28 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +* Calculate the <a href="http://blackswanfarming.com/cost-of-delay-divided-by-duration/" target="blank">CD3</a> (cost of delay/duration) and <a href="http://www.scaledagileframework.com/wsjf/" target
done

2017-02-23 10:30 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +	*	Planning and progress (jira, trello) – setup corresponding meetings
done

2017-02-23 10:30 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +	* Communication tool (slack, skype, email etc.)
done

2017-02-23 10:30 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +* Team set up is agreed with agile coach / scrum master / team-cut captain
done

2017-02-23 10:32 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +Acceptance Criteria:
the acceptance criteria define what the product contains after the we finished the story I think its fine

2017-02-23 10:34 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +**As a** Product Owner **I want** to set up teams quickly and efficiently in order to get them up ‘n’ running fast and deliver the highest value.
done

2017-02-23 10:36 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +It is the challenge for each team member to adapt quickly to new teams, skills and goals. I would like to share how we approach building stronger teams and to have a checklist for myself when a new t
its rewritten

2017-02-23 10:37 UTC, JTheilmann commented on _posts/blog/2017-02-22-team_cut_story.md
> +excerpt: A short story about how to measure a team cut experiment. We change teams a few times already – this article shows how can we learn which set up was actually more productive and how to perfo
does it feel better now?

2017-03-03 15:23 UTC, merged

2017-03-05 22:55 UTC, maciejwalkowiak commented on _posts/blog/2017-03-03-team_cut_story.md
> +* <a link="http://kanbantool.com/kanban-library/analytics-and-metrics/kanban-definition-of-lead-time-and-cycle-time#.WHdWULbhDBJ" target="blank">Cycle time</a>
In HTML use `href` instead of `link`. Otherwise link does not work. 
In Markdown you can (should) use document `[text](url)` format.